name: CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      # Allow GitHub to request an OIDC JWT ID token, for exchange with `aws-actions/configure-aws-credentials`
      # See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#updating-your-github-actions-workflow
      id-token: write

      # Required for `actions/checkout`
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
          cache: sbt

      # Seed the build number with last number from TeamCity.
      # This env var is used by the SBT build, and guardian/actions-riff-raff.
      # Set the value early, rather than `buildNumberOffset` in guardian/actions-riff-raff, to ensure each usage has the same number.
      # For some reason, it's not possible to mutate GITHUB_RUN_NUMBER, so set BUILD_NUMBER instead.
      - name: Set BUILD_NUMBER environment variable
        run: |
          LAST_TEAMCITY_BUILD=2360
          echo "BUILD_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))" >> $GITHUB_ENV

      - name: build + test
        env:
          # The GitHub runner has 7GB of RAM, lets give 4GB to Java.
          # See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources.
          JAVA_OPTS: -Xmx4g
        run: sbt clean scalafmtCheckAll scalafmtSbtCheck compile lib/test riffraff/test Universal/packageZipTarball

      - uses: guardian/actions-riff-raff@v2
        with:
          buildNumber: ${{ env.BUILD_NUMBER }}
          projectName: tools::riffraff
          configPath: riff-raff/riff-raff.yaml
          contentDirectories: |
            riff-raff:
              - riff-raff/bootstrap.sh
              - riff-raff/target/universal/riff-raff.tgz
